server:
  port: 8080

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
    ignore-ignored-migrations: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: NON_NULL
  main:
    banner-mode: "OFF"
  banner:
    location: banner.txt

  # valores padrão para rodar FORA de container (dev local)
  datasource:
    url: jdbc:mysql://localhost:3306/alagamentos?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 241103
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

openweathermap:
  url: https://api.openweathermap.org
  key: chaveteste
  lang: pt_br
  units: metric

predictionapi:
  url: http://localhost:8000
  path-predict: /predict

# ... seu conteúdo atual (mantém dev local em localhost) ...

---
spring:
  config:
    activate:
      on-profile: container
  datasource:
    url: jdbc:mysql://mysql:3306/alagamento?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: alagouai
    password: alagouai_pwd
  jpa:
    hibernate:
      ddl-auto: update

predictionapi:
  url: ${PY_SERVICE_URL:http://api-py:8000}

