server:
  port: 8080

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: NON_NULL
  main:
    banner-mode: "OFF"
  banner:
    location: banner.txt
#  profiles:
#    active: ${ENVIRONMENT:@spring.profiles.active@}


  datasource:
    url: jdbc:mysql://localhost:3306/alagamentos?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: senha
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # ou validate, none, create, create-drop, conforme o ambiente
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

openweathermap:
  url: https://api.openweathermap.org
  key: chave
  lang: pt_br
  units: metric